---
sidebar: sidebar 
permalink: xcp/xcp-bp-performance-tuning.html 
keywords: performance, tuning, operations, windows 
summary: このセクションでは、XCP 操作のパフォーマンスを向上させるのに役立ついくつかのチューニング パラメータについて説明します。 
---
= パフォーマンス調整
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このセクションでは、XCP 操作のパフォーマンスを向上させるのに役立ついくつかのチューニング パラメータについて説明します。

* スケーリングを向上させ、複数の XCP インスタンスにワークロードを分散するには、移行とデータ転送のために各 XCP インスタンスのサブフォルダーを分割します。
* XCP は最大限の CPU リソースを使用できます。CPU コアの数が多いほど、パフォーマンスが向上します。したがって、XCP サーバーにはさらに多くの CPU が必要です。弊社のラボでは 128 GB の RAM と 48 コアの CPU をテストしましたが、8 コアの CPU と 8 GB の RAM よりも優れたパフォーマンスが得られました。
* XCPコピーを `-parallel`オプションは CPU の数に基づいています。並列スレッドのデフォルトの数 (7) は、ほとんどの XCP データ転送および移行操作には十分な場合があります。 XCP Windows の場合、デフォルトでは並列プロセスの数は CPU の数と同じになります。最大数は `-parallel`オプションはコア数以下である必要があります。
* 10GbE はデータ転送の良いスタートです。ただし、25GbE と 100GbE でテストしたところ、データ転送速度が向上し、大きなファイル サイズのデータの転送に推奨されました。
* Azure NetApp Filesの場合、パフォーマンスはサービス レベルによって異なります。詳細については、 Azure NetApp Files のサービス レベルとパフォーマンスの詳細を示す次の表を参照してください。


|===
| サービス レベル | Standard | Premium | ウルトラ 


| スループット | 16MBps/テラバイト（TB） | 64MBps/TB | 128MBps/TB 


| ワークロードの種類 | 汎用ファイル共有、電子メール、ウェブ | BM、データベース、アプリケーション | レイテンシに敏感なアプリケーション 


| パフォーマンスの説明 | 標準パフォーマンス: 1TBあたり1,000 IOPS (16K I/O)、16MBps/TB | プレミアムパフォーマンス - 1TBあたり4,000 IOPS（16k I/O）および64MBps/TB | 極めて優れたパフォーマンス: 1TBあたり8,000 IOPS (16k I/O)、128MBps/TB 
|===
スループットとワークロードの種類に基づいて適切なサービス レベルを選択する必要があります。ほとんどのお客様は、プレミアム レベルから開始し、ワークロードに応じてサービス レベルを変更します。
