---
sidebar: sidebar 
permalink: xcp/xcp-bp-best-practices.html 
keywords: best practices, guidelines, recommendations, IMT 
summary: このセクションには、 NetApp XCP を使用してデータを移行するためのベスト プラクティス、ガイドライン、および推奨事項が記載されています。 
---
= ベストプラクティスのガイドラインと推奨事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
* IMTがサポートされている XCP クライアント オペレーティング システムを使用します。  IMT対応クライアントはNetAppによって認定されています。
* 移行を実行するには、Linux オペレーティング システムで XCP を root ユーザーとして実行します。xcp コマンドを sudo ユーザーとして実行できますが、XCP ではサポートされていません。
* クライアントごとに XCP のインスタンスを 1 つだけ実行します。技術的には、異なる場所から同じホスト上で XCP の複数のインスタンスを実行することは可能ですが、これはサポートされている方法ではありません。実際、多くのインスタンスを実行すると失敗する可能性があります。
* XCP NFS はライブ ソース データ セットからの移行が可能であり、この構成がサポートされています。ライブ ソース データ セットからの XCP SMB 移行はサポートされておらず、失敗する可能性があります。
* 障害発生時にスナップショット名に基づいて増分移行パスを簡単に作成できるように、増分同期ごとに異なる名前で新しいスナップショットを作成するのがベストプラクティスです。
* スナップショットベースの移行を実行している場合は、カットオーバーまでスナップショットベースの移行を継続することがベスト プラクティスです。
* ファイルが 1,000 万個以上あり、データの増分変更が 50% を超える場合は、インストールおよび管理ガイドの最小推奨事項よりも多くのコア数とメモリを使用するのがベスト プラクティスです。

