---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-ps-consider.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: これは、 ONTAPベースのサイバーボールトを構成、強化、検証するためのNetApp ONTAPソリューションです。 
---
= その他の考慮事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAPベースのサイバー ボールトを設計および導入する際には、追加の考慮事項があります。



== 容量サイジングの考慮事項

ONTAPサイバー ボールトの宛先ボリュームに必要なディスク領域の量はさまざまな要因によって異なりますが、最も重要なのはソース ボリュームのデータの変更率です。宛先ボリュームのバックアップ スケジュールとスナップショット スケジュールは両方とも宛先ボリュームのディスク使用量に影響し、ソース ボリュームの変更率は一定にならない可能性があります。エンドユーザーやアプリケーションの動作の将来的な変化に対応するために必要な容量に加えて、追加のストレージ容量のバッファーを用意しておくことをお勧めします。

ONTAPで 1 か月間の保持関係のサイズを決定するには、プライマリ データセットのサイズ、データ変更率（日次変更率）、重複排除と圧縮による節約（該当する場合）など、いくつかの要素に基づいてストレージ要件を計算する必要があります。

手順は次のとおりです。

最初のステップは、サイバー ボールトで保護しているソース ボリュームのサイズを確認することです。これは、サイバー ボールトの宛先に最初に複製されるデータの基本量です。次に、データセットの毎日の変化率を推定します。これは毎日変更されるデータの割合です。データがどれだけ動的であるかをよく理解することが重要です。

例えば：

* プライマリデータセットのサイズ = 5TB
* 日次変化率 = 5% (0.05)
* 重複排除と圧縮効率 = 50% (0.50)


それでは計算を見てみましょう。

* 毎日のデータ変化率を計算します。
+
`Changed data per day = 5000 * 5% = 250GB`

* 30 日間の変更されたデータの合計を計算します。
+
`Total changed data in 30 days = 250 GB * 30 = 7.5TB`

* 必要な合計ストレージを計算します。
+
`TOTAL = 5TB + 7.5TB = 12.5TB`

* 重複排除と圧縮による節約を適用します。
+
`EFFECTIVE = 12.5TB * 50% = 6.25TB`



*ストレージニーズの概要*

* 効率性がなければ、サイバー ボールト データの 30 日分を保存するには *12.5 TB* が必要になります。
* 効率が 50% の場合: 重複排除と圧縮後に *6.25 TB* のストレージが必要になります。



NOTE: スナップショット コピーではメタデータによる追加のオーバーヘッドが発生する可能性がありますが、通常はそれほど大きくありません。


NOTE: 1 日に複数のバックアップが作成される場合は、1 日に作成される Snapshot コピーの数に応じて計算を調整します。


NOTE: 時間の経過に伴うデータの増加を考慮して、サイズが将来にも対応できることを確認します。



== プライマリ/ソースへのパフォーマンスの影響

データ転送はプル操作であるため、プライマリ ストレージのパフォーマンスへの影響は、ワークロード、データ量、およびバックアップの頻度によって異なります。ただし、データ転送はデータ保護とバックアップ タスクをサイバー ボールト ストレージ システムにオフロードするように設計されているため、プライマリ システムへの全体的なパフォーマンスへの影響は通常は中程度で管理可能です。初期の関係のセットアップと最初の完全バックアップ中に、大量のデータがプライマリ システムからサイバー ボールト システム ( SnapLock Complianceボリューム) に転送されます。これにより、プライマリ システムのネットワーク トラフィックと I/O 負荷が増加する可能性があります。最初の完全バックアップが完了すると、 ONTAP は最後のバックアップ以降に変更されたブロックを追跡して転送するだけで済みます。これにより、初期レプリケーションと比較して I/O 負荷が大幅に軽減されます。増分更新は効率的であり、プライマリ ストレージのパフォーマンスへの影響は最小限に抑えられます。ボールト プロセスはバックグラウンドで実行されるため、プライマリ システムの運用ワークロードに干渉する可能性が軽減されます。

* 追加の負荷を処理するために十分なリソース (CPU、メモリ、IOPS) がストレージ システムにあることを確認すると、パフォーマンスへの影響が軽減されます。

