---
sidebar: sidebar 
permalink: automation/automation-introduction.html 
summary: NetAppソリューションの自動化により、顧客は多くの一般的なインフラストラクチャおよびアプリケーション タスクの導入、構成、実行を自動化できます。 
keywords: netapp, solutions, automation, ansible, terraform 
---
= NetAppソリューション自動化
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetAppソリューションの自動化により、顧客は多くの一般的なインフラストラクチャおよびアプリケーション タスクの導入、構成、実行を自動化できます。



== はじめに

NetApp は、今日のビジネス課題に対応するソリューションを提供するにあたり、次の目標を掲げてソリューションを提供しています。

* 検証済みの展開および構成手順の提供、
* 簡単に消費できるソリューションを提供し、
* 予測可能な結果をもたらし、簡単に繰り返し実行でき、顧客の企業全体で拡張可能なソリューション展開を提供します。


これらの目標を達成するには、当社のソリューションを通じて提供されるインフラストラクチャやアプリケーションの導入と構成が自動化によって簡素化されることが最も重要です。  NetApp は、自動化を通じてソリューションの使用を簡素化することに取り組んでいます。

NetAppソリューションは、Red Hat Ansible、HashiCorp Terraform、Microsoft Powershell などのオープンソースの自動化ツールを活用して、アプリケーションの導入、クラウドのプロビジョニング、構成管理、その他多くの一般的な IT タスクを自動化する機能を備えています。  NetApp のソリューションは、公開されている自動化アーティファクトを活用し、またNetAppが作成した自動化を提供することで、ソリューションの全体的な導入を簡素化します。

自動化機能が利用可能な場合、ソリューション資料では、特定の自動化ツールを使用してソリューションまたはソリューションのステップを自動化するプロセスをユーザーに案内します。
